services:
  web:
    image: python:3
    command: ['python3', '-m', 'flask', 'run', '--port=4242', '--host=0.0.0.0']
    ports: ['4242:4242']
    environment:
      - FLASK_APP=server.py
    working_dir: /app/server/python
    volumes:
      - ../..:/app
      - .local:/root/.local

  stripe:
    image: stripe/stripe-cli
    command: ['listen', '--forward-to', 'http://web:4242/stripe-webhook']
    volumes:
      - .config/stripe:/root/.config/stripe
